version: "3.8"

services:
    frontend:
        build:
            context: ./RealTimeAppClient
            dockerfile: Dockerfile
        environment:
            - DB_FILE_PATH=/app/RealTimeApp.db
        ports:
            - "3000:80"
        depends_on:
            - backend

    backend:
        build:
            context: ./RealTimeAppServer
            dockerfile: Dockerfile
        ports:
            - "5003:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
