version: "3.8"

services:
    frontend:
        build:
            context: ./RealTimeAppClient
            dockerfile: Dockerfile
            args:
                - REACT_APP_API_BASE_URL=http://localhost:5003
        ports:
            - "3000:80"
        depends_on:
            - backend

    backend:
        build:
            context: ./RealTimeAppServer
            dockerfile: Dockerfile
        ports:
            - "5003:80"
        volumes:
            - ./RealTimeAppServer/RealTimeApp.db:/app/RealTimeApp.db
        environment:
            - DB_FILE_PATH=/app/RealTimeApp.db
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
